folder_data : "/Users/christovis/Documents/InternetGovernance/bigbang-graphql/data"
folder_proj : "/Users/christovis/Documents/InternetGovernance/bigbang-graphql"
# uri_mysql : "mysql+pymysql://root:AsS0%rteD@localhost:3306/bigbang_test"
# password_mysql : "AsS0%rteD"
